import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ProductserviceService {

  
  constructor() { }
  getProduct(): any[] {
    return [
      // Fruits
      { productId: 1, productName: "Apple",weight:"1 Kg", productCategory: "Fruits", productPrice: "120", image: "https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Apple can keeps your taste buds happy and satisfied.",delivery:"Free delivery" },
      { productId: 2, productName: "Lemons",weight:"1 Kg", productCategory: "Fruits", productPrice: "90", image: "https://images.pexels.com/photos/1414110/pexels-photo-1414110.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "When life gives you Lemons, make Lemonade ",delivery:"Free delivery" },
      { productId: 3, productName: "Mangoes",weight:"1 Kg", productCategory: "Fruits", productPrice: "60", image: "https://images.pexels.com/photos/7156058/pexels-photo-7156058.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Mangoes are a tropical paradise in your mouth with juicy sweetness",delivery:"Free delivery" },
      { productId: 4, productName: "Strawberry",weight:"1 Kg", productCategory: "Fruits", productPrice: "590", image: "https://images.pexels.com/photos/4038803/pexels-photo-4038803.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Strawberries are red. They're good for your blood." ,delivery:"Free delivery"},
      { productId: 5, productName: "Watermelon",weight:"1 Kg", productCategory: "Fruits", productPrice: "85", image: "https://images.pexels.com/photos/1313267/pexels-photo-1313267.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Hot summer days ahead. It's time for a lot of watermelons.",delivery:"Free delivery" },
      { productId: 6, productName: "Guava",weight:"1 Kg", productCategory: "Fruits", productPrice: "60", image: "https://images.pexels.com/photos/10450721/pexels-photo-10450721.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "There's nothing quite like the sweet, juicy flavor of a guava.",delivery:"Free delivery" },
      { productId: 7, productName: "Banana",weight:"1 Kg", productCategory: "Fruits", productPrice: "45", image: "https://images.pexels.com/photos/5342631/pexels-photo-5342631.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Eat banana in a break to get breakfree nutrients" ,delivery:"Free delivery"},
      { productId: 8, productName: "Grapes ",weight:"1 Kg", productCategory: "Fruits", productPrice: "370", image: "https://images.pexels.com/photos/545036/pexels-photo-545036.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Grapes are nature's candy - a delicious and healthy treat",delivery:"Free delivery" },
      { productId: 9, productName: "Plums",weight:"1 Kg", productCategory: "Fruits", productPrice: "325", image: "https://images.pexels.com/photos/1268122/pexels-photo-1268122.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "A perfectly ripe plum is one of life's simple pleasures.",delivery:"Free delivery" },
      { productId: 10, productName: "Kiwi",weight:"1 Kg", productCategory: "Fruits", productPrice: "400", image: "https://images.pexels.com/photos/54370/pexels-photo-54370.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Satisfy your sweet tooth and boost your health with delicious kiwi!",delivery:"Free delivery" },
      { productId: 11, productName: "Pineapple",weight:"1 Kg", productCategory: "Fruits", productPrice: "190", image: "https://images.pexels.com/photos/4195522/pexels-photo-4195522.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Get your daily dose of vitamin C and fiber with pineapples!" ,delivery:"Free delivery"},
      { productId: 12, productName: "Jackfruit",weight:"1 Kg", productCategory: "Fruits", productPrice: "230", image: "https://media.istockphoto.com/id/1369037190/photo/single-object-of-jackfruit-isolated-on-white-background.jpg?b=1&s=612x612&w=0&k=20&c=S2N6qfAskqOkAWsQdQknNTEB-zMwYPKbrCJXHsFFPx4=",
      description: "If you've never tasted jackfruit, you're missing out a fruit adventure!",delivery:"Free delivery" },
      { productId: 13, productName: "Sapota",weight:"1 Kg", productCategory: "Fruits", productPrice: "86", image: "https://thumbs.dreamstime.com/b/sapodilla-plum-sapota-manilkara-zapota-l-p-royen-medicinal-properties-39884887.jp",
      description: "Sapota is nature's dessert, packed with flavor in every bite." ,delivery:"Free delivery"},
      { productId: 14, productName: "Dragonfruit ",weight:"1 Kg", productCategory: "Fruits", productPrice: "192", image: "https://thumbs.dreamstime.com/b/dragon-fruit-isolated-white-background-57974465.jpg",
      description: "Dragonfruit is both humble and luxurious, with its simple appearance",delivery:"Free delivery" },
      { productId: 15, productName: "Fig",weight:"1 Kg", productCategory: "Fruits", productPrice: "353", image: "https://images.pexels.com/photos/5475168/pexels-photo-5475168.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Fig is a fruit that's worth wait - its  flavor is a reward for patience." ,delivery:"Free delivery"},
      { productId: 16, productName: "Gooseberry",weight:"1 Kg", productCategory: "Fruits", productPrice: "280", image: "https://thumbs.dreamstime.com/b/indian-gooseberry-isolated-white-background-indian-gooseberry-isolated-white-background-180698765.jpg",
      description: "Once you try this Gooseberry, you'll wonder how you missed it." ,delivery:"Free delivery"},
      { productId: 17, productName: "Mulberry",weight:"1 Kg", productCategory: "Fruits", productPrice: "195", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdQ-9ou8DWL1tuLsQMwOKLPWCe_EPxa3qlquIqiVtsug&usqp=CAU&ec=48600112",
      description: "Don't let the small size fool you - it's a pack of big punch flavor",delivery:"Free delivery" },
      { productId: 18, productName: "Pear",weight:"1 Kg", productCategory: "Fruits", productPrice: "150", image: "https://images.pexels.com/photos/568471/pexels-photo-568471.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "When life gets busy, a juicy, refreshing pear is the perfect pick-me-up",delivery:"Free delivery" },
      { productId: 19, productName: "Papaya",weight:"1 Kg", productCategory: "Fruits", productPrice: "175", image: "https://thumbs.dreamstime.com/b/papaya-28834146.jpg",
      description: "Add a little Papaya  to your life and you'll see how amazing it would be.",delivery:"Free delivery" },
      { productId: 20, productName: "pomegranate",weight:"1 Kg", productCategory: "Fruits", productPrice: "180", image: "https://images.pexels.com/photos/6956386/pexels-photo-6956386.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Eating a pomegranate is like unwrapping a gift from nature",delivery:"Free delivery" },
      { productId: 21, productName: "Cashew Fruit",weight:"1 Kg", productCategory: "Fruits", productPrice: "215", image: "https://images.pexels.com/photos/5768033/pexels-photo-5768033.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Cashew fruit - those who try it are in for a real treat",delivery:"Free delivery" },
      { productId: 22, productName: "Redbanana",weight:"1 Kg", productCategory: "Fruits", productPrice: "165", image: "https://thumbs.dreamstime.com/b/red-banana-red-banana-isolated-over-white-background-100906249.jpg",
      description: "Red bananas are the ultimate indulgence for fruit lovers everywhere.",delivery:"Free delivery" },
      { productId: 23, productName: "Star Fruit",weight:"1 Kg", productCategory: "Fruits", productPrice: "280", image: "https://thumbs.dreamstime.com/b/starfruit-18211983.jpg",
      description: "A fruit that's sure to make your taste buds sing !",delivery:"Free delivery" },
      { productId: 24, productName: "Ice Apple ",weight:"1 Kg", productCategory: "Fruits", productPrice: "240", image: "https://www.deccanherald.com/sites/dh/files/gallery_images/file7ffns3xq813bh4u33yi.jpg",
      description: "Cool down this summer with the refreshing taste of ice apple",delivery:"Free delivery" },
      { productId: 25, productName: "Orange",weight:"1 Kg", productCategory: "Fruits", productPrice: "160", image: "https://images.pexels.com/photos/161559/background-bitter-breakfast-bright-161559.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Don't settle for boring fruits - try the exotic and delicious Orange",delivery:"Free delivery" },
      { productId: 26, productName: "Amla",weight:"1 Kg", productCategory: "Fruits", productPrice: "150", image: "https://thumbs.dreamstime.com/b/fresh-amla-small-brown-bowl-34380795.jpg",
      description: "Looking for a new and exciting fruit to try? Give amla a chance",delivery:"Free delivery" },
      { productId: 27, productName: "Mulberry",weight:"1 Kg", productCategory: "Fruits", productPrice: "235", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdQ-9ou8DWL1tuLsQMwOKLPWCe_EPxa3qlquIqiVtsug&usqp=CAU&ec=48600112",
      description: "Get ready to fall in love with the sweet & juicy flavor of mulberrie",delivery:"Free delivery" },
      { productId: 28, productName: "Pear",weight:"1 Kg", productCategory: "Fruits", productPrice: "165", image: "https://thumbs.dreamstime.com/b/red-yellow-pear-fruit-leaf-isolated-white-clipping-path-78863322.jpg",
      description: "If you're looking for a tasty & healthy fruit to add to your diet, Here you go",delivery:"Free delivery" },
      { productId: 29, productName: "Rose Apple",weight:"1 Kg", productCategory: "Fruits", productPrice: "170", image: "https://thumbs.dreamstime.com/b/rose-apple-18399276.jpg",
      description: "Step out of your comfort zone and try something new with Rose Apples!",delivery:"Free delivery" },
      { productId: 30, productName: "Avacado",weight:"1 Kg", productCategory: "Fruits", productPrice: "310", image: "https://images.pexels.com/photos/2095924/pexels-photo-2095924.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Avocado -fruit that's as versatile as it is delicious",delivery:"Free delivery" },
      // Vegetables
      { productId: 31, productName: "Tomato",weight:"1 Kg", productCategory: "Vegetables", productPrice: "25", image: "https://images.pexels.com/photos/53588/tomatoes-vegetables-food-frisch-53588.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "The tomato offers its gift of fiery color and cool completeness.",delivery:"Free delivery" },
      { productId: 32, productName: "Onion",weight:"1 Kg", productCategory: "Vegetables", productPrice: "50", image: "https://images.pexels.com/photos/4197444/pexels-photo-4197444.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Onions are the spice of life." ,delivery:"Free delivery"},
      { productId: 33, productName: "Potato", weight:"1 Kg",productCategory: "Vegetables", productPrice: "35", image: "https://images.pexels.com/photos/775707/pexels-photo-775707.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Healthy veggies, healthy planet" ,delivery:"Free delivery"},
      { productId: 34, productName: "Turnip ",weight:"1 Kg", productCategory: "Vegetables", productPrice: "92", image: "https://images.pexels.com/photos/13133610/pexels-photo-13133610.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Veggies: the ultimate mood booster.",delivery:"Free delivery" },
      { productId: 35, productName: "Pumpkin",weight:"1 Kg", productCategory: "Vegetables", productPrice: "153", image: "https://images.pexels.com/photos/673073/pexels-photo-673073.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Eat more veggies, feel better." ,delivery:"Free delivery"},
      { productId: 36, productName: "Garlic",weight:"1 Kg", productCategory: "Vegetables", productPrice: "80", image: "https://images.pexels.com/photos/4197487/pexels-photo-4197487.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "It is like a secret weapon in the kitchen. It adds depth and flavor to dishes.",delivery:"Free delivery" },
      { productId: 37, productName: "Ginger",weight:"1 Kg", productCategory: "Vegetables", productPrice: "95", image: "https://images.pexels.com/photos/161556/ginger-plant-asia-rhizome-161556.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Ginger can be a little miracle worker for your body. It can help ease nausea, reduce inflammation.",delivery:"Free delivery" },
      { productId: 38, productName: "Green chili",weight:"1 Kg", productCategory: "Vegetables", productPrice: "30", image: "https://images.pexels.com/photos/2893540/pexels-photo-2893540.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Whether you're a fan of spicy food or not, green chili is worth giving a try.",delivery:"Free delivery" },
      { productId: 39, productName: "Beans",weight:"1 Kg", productCategory: "Vegetables", productPrice: "45", image: "https://images.pexels.com/photos/768092/pexels-photo-768092.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "For those who are looking for a way to add some plant-based protein to your diet",delivery:"Free delivery" },
      { productId: 40, productName: "Radish",weight:"1 Kg", productCategory: "Vegetables", productPrice: "80", image: "https://images.pexels.com/photos/244393/pexels-photo-244393.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Here is the little wake-up call for your taste buds" ,delivery:"Free delivery"},
      { productId: 41, productName: "Lady finger",weight:"1 Kg", productCategory: "Vegetables", productPrice: "35", image: "https://media.istockphoto.com/id/478680790/photo/fresh-bunch-of-okra-vegetable-isolated-on-white-background.jpg?b=1&s=612x612&w=0&k=20&c=AUJNjwNM74UcDXz7JDPqN-Htlc2Mhwv6lWwgGWu3nQI=",
      description: "Little nutritional powerhouses to keep you healthy and strong",delivery:"Free delivery" },
      { productId: 42, productName: "Peans",weight:"1 Kg", productCategory: "Vegetables", productPrice: "65", image: "https://images.pexels.com/photos/768092/pexels-photo-768092.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Want to add some color to your dishes, peas are a great choice.",delivery:"Free delivery" },
      { productId: 43, productName: "Broccoli",weight:"1 Kg", productCategory: "Vegetables", productPrice: "80", image: "https://images.pexels.com/photos/161514/brocoli-vegetables-salad-green-161514.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Little green tree, full of flavor and nutrition.",delivery:"Free delivery" },
      { productId: 44, productName: "Cauliflower ",weight:"1 Kg", productCategory: "Vegetables", productPrice: "40", image: "https://images.pexels.com/photos/4963721/pexels-photo-4963721.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Blank slate for your cooking, ready to be transformed into  delicious dishes , here you go !" ,delivery:"Free delivery"},
      { productId: 45, productName: "Carrot",weight:"1 Kg", productCategory: "Vegetables", productPrice: "60", image: "https://images.pexels.com/photos/6740693/pexels-photo-6740693.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Carrot can be used in countless ways to add depth and richness to your dishes ",delivery:"Free delivery" },
      { productId: 46, productName: "Capsicum",weight:"1 Kg", productCategory: "Vegetables", productPrice: "50", image: "https://images.pexels.com/photos/7473491/pexels-photo-7473491.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Are you looking for a way to add some crunch to your dishes, Here you go" ,delivery:"Free delivery"},
      { productId: 47, productName: "Cabbage",weight:"1 Kg", productCategory: "Vegetables", productPrice: "35", image: "https://images.pexels.com/photos/13796758/pexels-photo-13796758.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Cabbage is a powerful vegetable that can help a healthy immune system",delivery:"Free delivery" },
      { productId: 48, productName: "Brinjal",weight:"1 Kg", productCategory: "Vegetables", productPrice: "65", image: "https://images.pexels.com/photos/1340856/pexels-photo-1340856.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "People either love or hate it. But when it's cooked well, it's a true delight." ,delivery:"Free delivery"},
      { productId: 49, productName: "Mushroom",weight:"1 Kg", productCategory: "Vegetables", productPrice: "70", image: "https://images.pexels.com/photos/109215/pexels-photo-109215.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Mushrooms are a great source of plant-based protein" ,delivery:"Free delivery"},
      { productId: 50, productName: "Tamarind",weight:"1 Kg", productCategory: "Vegetables", productPrice: "110", image: "https://images.pexels.com/photos/11536825/pexels-photo-11536825.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Describe the flavor is hard, if you taste it, you'll never forget it.",delivery:"Free delivery" },
      { productId: 51, productName: "Beetroot",weight:"1 Kg", productCategory: "Vegetables", productPrice: "115", image: "https://images.pexels.com/photos/5758691/pexels-photo-5758691.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Beetroot is a great source of energy and helps to boost stamina",delivery:"Free delivery" },
      { productId: 52, productName: "Coconut",weight:"1 Kg", productCategory: "Vegetables", productPrice: "65", image: "https://images.pexels.com/photos/3986706/pexels-photo-3986706.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Red bananas are the ultimate indulgence for fruit lovers everywhere." ,delivery:"Free delivery"},
      { productId: 53, productName: "Sweet Potato",weight:"1 Kg", productCategory: "Vegetables", productPrice: "80", image: "https://images.pexels.com/photos/4617475/pexels-photo-4617475.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "A fruit that's sure to make your taste buds sing !" ,delivery:"Free delivery"},
      { productId: 54, productName: "Corn",weight:"1 Kg", productCategory: "Vegetables", productPrice: "40", image: "https://images.pexels.com/photos/547263/pexels-photo-547263.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Cool down this summer with the refreshing taste of Corn",delivery:"Free delivery" },
      { productId: 55, productName: "Soya Bean",weight:"1 Kg", productCategory: "Vegetables", productPrice: "60", image: "https://images.pexels.com/photos/4518608/pexels-photo-4518608.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Don't settle for boring Vegies - try the exotic and delicious Soya Bean",delivery:"Free delivery" },
      // Dryfruits
      { productId: 56, productName: "Almonds",weight:"1 Kg", productCategory: "Dryfruits", productPrice: "350", image: "https://images.pexels.com/photos/57042/pexels-photo-57042.jpeg?auto=compress&cs=tinysrgb&w=400",
      description: "Nourish your body and soul with these wholesome treats." ,delivery:"Free delivery"},
      { productId: 57, productName: "Cashews",weight:"1 Kg", productCategory: "Dryfruits", productPrice: "435", image: "https://images.pexels.com/photos/9017852/pexels-photo-9017852.jpeg?auto=compress&cs=tinysrgb&w=400&lazy=load",
      description: "Healthy snacking never tasted this good." ,delivery:"Free delivery"},
      { productId: 58, productName: "Pistachios",weight:"1 Kg", productCategory: "Dryfruits", productPrice: "565", image: "https://images.pexels.com/photos/1799307/pexels-photo-1799307.jpeg?auto=compress&cs=tinysrgb&w=400&lazy=load",
      description: "Nature's candy, now at your screen tap" ,delivery:"Free delivery"},
      { productId: 59, productName: "Walnuts",weight:"1 Kg", productCategory: "Dryfruits", productPrice: "470", image: "https://images.pexels.com/photos/3969097/pexels-photo-3969097.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "A handful of goodness in every bite.  " ,delivery:"Free delivery"},
      { productId: 60, productName: "Peanuts",weight:"1 Kg", productCategory: "Dryfruits", productPrice: "110", image: "https://images.pexels.com/photos/4202959/pexels-photo-4202959.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Fuel your day with the power of nuts and fruits." ,delivery:"Free delivery"},
      { productId: 61, productName: "Dry Grapes",weight:"1 Kg", productCategory: "Dryfruits", productPrice: "315", image: "https://images.pexels.com/photos/4499228/pexels-photo-4499228.jpeg?auto=compress&cs=tinysrgb&w=300",
      description: "Good things come in small packages, like these dry fruits.",delivery:"Free delivery" },
      { productId: 62, productName: "Dates",weight:"1 Kg", productCategory: "Dryfruits", productPrice: "365", image: "https://images.pexels.com/photos/3993529/pexels-photo-3993529.jpeg?auto=compress&cs=tinysrgb&w=1600",
      description: "For a snack that's as sweet as you are, try these dry fruits.",delivery:"Free delivery" },
      { productId: 63, productName: "Figs",weight:"1 Kg", productCategory: "Dryfruits", productPrice: "480", image: "https://images.pexels.com/photos/5475169/pexels-photo-5475169.jpeg?auto=compress&cs=tinysrgb&w=1600",
      description: "Satisfy your cravings without sacrificing your health.!" ,delivery:"Free delivery"},
      { productId: 64, productName: "Apricots",weight:"1 Kg", productCategory: "Dryfruits", productPrice: "340", image: "https://images.pexels.com/photos/5425018/pexels-photo-5425018.jpeg?auto=compress&cs=tinysrgb&w=1600",
      description: "A snack that's both delicious and nutritious" ,delivery:"Free delivery"},
      { productId: 65, productName: "Prunes",weight:"1 Kg", productCategory: "Dryfruits", productPrice: "260", image: "https://images.pexels.com/photos/12945019/pexels-photo-12945019.jpeg?auto=compress&cs=tinysrgb&w=1600",
      description: "Snack smarter with these wholesome dry fruits.",delivery:"Free delivery" },
      { productId: 66, productName: "Pine Nuts",weight:"1 Kg", productCategory: "Dryfruits", productPrice: "350", image: "https://images.pexels.com/photos/10433520/pexels-photo-10433520.jpeg?auto=compress&cs=tinysrgb&w=1600",
      description: "The perfect snack to fuel your busy lifestyle" ,delivery:"Free delivery"},
      { productId: 67, productName: "Cashews",weight:"1 Kg", productCategory: "Dryfruits", productPrice: "435", image: "https://images.pexels.com/photos/9017852/pexels-photo-9017852.jpeg?auto=compress&cs=tinysrgb&w=400&lazy=load",
      description: "Healthy snacking has never been so satisfying.",delivery:"Free delivery" },
      { productId: 68, productName: "Pistachios",weight:"1 Kg", productCategory: "Dryfruits", productPrice: "565", image: "https://images.pexels.com/photos/1799307/pexels-photo-1799307.jpeg?auto=compress&cs=tinysrgb&w=400&lazy=load",
      description: "Experience the best of nature's bounty with these dry fruits." ,delivery:"Free delivery"},
      { productId: 69, productName: "Lotus Seeds",weight:"1 Kg", productCategory: "Dryfruits", productPrice: "370", image: "https://images.pexels.com/photos/13526026/pexels-photo-13526026.jpeg?auto=compress&cs=tinysrgb&w=1600",
      description: "A snack that's naturally sweet, and full of goodness" ,delivery:"Free delivery"},
      { productId: 70, productName: "Sesame Seeds",weight:"1 Kg", productCategory: "Dryfruits", productPrice: "110", image: "https://images.pexels.com/photos/938699/pexels-photo-938699.jpeg?auto=compress&cs=tinysrgb&w=1600",
      description: "Healthy snacking never tasted this good.",delivery:"Free delivery" },
    //  Greens
      { productId: 71, productName: "Spinach",weight:"1 Kg", productCategory: "Greens", productPrice: "30", image: "https://cdn.pixabay.com/photo/2018/09/27/22/37/spinach-3708115__340.jpg",
      description: "Greens for the win, always.",delivery:"Free delivery" },
      { productId: 72, productName: "Fenugreek leaves",weight:"1 Kg", productCategory: "Greens", productPrice: "25", image: "https://cdn.pixabay.com/photo/2017/11/09/10/08/fenugreek-2932921__340.jpg",
      description: "Eating greens, feeling good." ,delivery:"Free delivery"},
      { productId: 73, productName: "Mustard greens",weight:"1 Kg", productCategory: "Greens", productPrice: "46", image: "https://cdn.pixabay.com/photo/2019/07/03/16/47/czosnaczek-4315006__340.jpg",
      description: "Nourish yourself with leafy greens.",delivery:"Free delivery" },
      { productId: 74, productName: "Amaranth leaves ",weight:"1 Kg", productCategory: "Greens", productPrice: "32", image: "https://cdn.pixabay.com/photo/2022/03/01/13/38/edible-amaranth-7041330__340.jpg",
      description: "Get your greens for a natural energy boost." ,delivery:"Free delivery"},
      { productId: 75, productName: "Dill leaves",weight:"1 Kg", productCategory: "Greens", productPrice: "53", image: "https://cdn.pixabay.com/photo/2019/08/11/19/37/plants-4399784__340.jpg",
      description: "Green up your life with leafy goodness." ,delivery:"Free delivery"},
      { productId: 76, productName: "Drumstick leaves",weight:"1 Kg", productCategory: "Greens", productPrice: "40", image: "https://images.pexels.com/photos/5750575/pexels-photo-5750575.jpeg?auto=compress&cs=tinysrgb&w=1600",
      description: "Eating greens is an act of self-care.",delivery:"Free delivery" },
      { productId: 77, productName: "Basella ",weight:"1 Kg", productCategory: "Greens", productPrice: "35", image: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Basella_alba-2.JPG",
      description: "Go green for a happy, healthy life!" ,delivery:"Free delivery"},
      { productId: 78, productName: "Curry leaves",weight:"1 Kg", productCategory: "Greens", productPrice: "30", image: "https://static.toiimg.com/photo/64996995.cms",
      description: "Eating greens is a smart investment in your health.",delivery:"Free delivery" },
      { productId: 79, productName: "Cilantro",weight:"1 Kg", productCategory: "Greens", productPrice: "25", image: "https://cdn.pixabay.com/photo/2016/03/29/01/06/cilantro-1287301__340.jpg",
      description: "The freshness of green leaves is unbeatable",delivery:"Free delivery" },
      { productId: 80, productName: "Mint",weight:"1 Kg", productCategory: "Greens", productPrice: "40", image: "https://cdn.pixabay.com/photo/2017/07/26/05/43/herb-2540568__340.png",
      description: "Add green leaves to your plate for a boost of energy" ,delivery:"Free delivery"},
      { productId: 81, productName: "Bottle gourd leaves",weight:"1 Kg", productCategory: "Greens", productPrice: "45", image: "https://cdn.pixabay.com/photo/2017/10/21/03/13/bottle-gourd-leaves-2873676__340.jpg",
      description: "The perfect way to add a touch of freshness to any dish",delivery:"Free delivery" },
      { productId: 82, productName: "Pumpkin leaves ",weight:"1 Kg", productCategory: "Greens", productPrice: "35", image: "https://cdn.pixabay.com/photo/2017/01/20/09/43/flower-1994381__340.jpg",
      description: "Eating leaves is like a celebration of nature's bounty" ,delivery:"Free delivery"},
      { productId: 83, productName: "Radish greens ",weight:"1 Kg", productCategory: "Greens", productPrice: "40", image: "https://cdn.pixabay.com/photo/2020/04/23/13/35/lettuce-5082546__340.jpg",
      description: "Eating green leaves is like feeding your body sunshine.!",delivery:"Free delivery" },
      { productId: 84, productName: "Banana leaves",weight:"1 Kg", productCategory: "Greens", productPrice: "30", image: "https://cdn.pixabay.com/photo/2019/07/01/04/38/banana-4309166__340.jpg",
      description: "The chlorophyll in green leaves helps detoxify and cleanse the body",delivery:"Free delivery" },
      { productId: 85, productName: "Onion leaves",weight:"1 Kg", productCategory: "Greens", productPrice: "25", image: "https://3.imimg.com/data3/HT/PG/MY-5485421/green-onion-leaves-500x500.png",
      description: "Eating greens is the green signal for a healthy body." ,delivery:"Free delivery"} 
    ];
  }

}
